catalog/urls.py
from django.urls import path

from catalog import views

urlpatterns = [
    path("", views.index, name="index"),
    path("index.html", views.index, name="home"),
    path("ping.html", views.index, name="ping"),
    path("login.html", views.login, name="login"),
    path("about.html", views.index, name="about"),
    path("stats/", views.PingView.as_view(), name="stats"),
    path("ping/", views.PingView.as_view(), name="ping"),
    path("projects/", views.ProjectsView.as_view(), name="projects"),
    path("project/<uuid:id>/", views.ProjectView.as_view(), name="project"),
    path("techstack/", views.TechStackView.as_view(), name="techstack"),
    path("techelement/<uuid:id>/", views.TechElementView.as_view(), name="techelem"),
    path("unique_url/", views.get_unique_url, name="unique_url"),
    path("your_data/", views.get_your_data, name="session_data"),
    path("your_data/<int:user_id>", views.get_your_data, name="session_data"),
]

landing_page/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic import RedirectView

from catalog import views

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    ###
    # Admin related urls
    ###
    path(
        "admin/password_reset/",
        auth_views.PasswordResetView.as_view(),
        name="admin_password_reset",
    ),
    path(
        "admin/password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

urlpatterns += [
    path("home/", include(("catalog.urls", "catalog"), namespace="catalog")),
    # All Auth urls
    path("accounts/", include("allauth.urls")),
]

# The default root url should point to catalog
urlpatterns += [
    path("", RedirectView.as_view(url="home/", permanent=False)),
    path("io/<str:unique_url>", views.get_io_forward, name="io_forward"),
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "catalog.views.handler404"
# handler500 = 'catalog.views.handler404'

catalog/models.py
from __future__ import annotations

from importlib.resources import _

from django.conf import settings
from django.contrib.sessions.models import Session
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.safestring import mark_safe
import uuid


class AppAuthor(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=250)
    email = models.EmailField()

    def __str__(self):
        return f"{self.name} -- {str(self.id)[:5]}"


class Project(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=250)
    description = models.TextField(max_length=2**14)
    active = models.BooleanField()
    link = models.URLField()
    created = models.DateField(auto_now_add=False, blank=False)
    view_level = models.IntegerField(default=1)
    author = models.ForeignKey("AppAuthor", on_delete=models.SET_NULL, null=True)
    techstack = models.ManyToManyField("TechElement")
    media = models.ManyToManyField("Media")

    DEV_STATUS = (
        ("m", "Maintained"),
        ("f", "Finalized"),
        ("d", "Deprecated"),
        ("p", "Planned"),
    )

    status = models.CharField(
        max_length=1,
        choices=DEV_STATUS,
        blank=True,
        default="p",
        help_text="Project status",
    )

    def __str__(self):
        return f"{self.name} -- {str(self.id)[:5]}"

    def escape_name(self):
        return str(self.name).replace(" ", "_")

    class Meta:
        ordering = ["-created"]


class TechElement(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=250)
    icon_src = models.URLField(blank=True)
    svg = models.TextField(blank=True)

    def __str__(self) -> str:
        return f"{self.name} -- {str(self.id)[:5]}"

    @mark_safe
    def icon_to_html(self) -> str | None:
        if self.svg is not None and len(self.svg):
            return f"""
            <div class="img-full">
            <svg id=\"{self.name}-svg\" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 51 51" preserveAspectRatio="none">
             {self.svg}
            </svg>
            </div>
            """
        elif self.icon_src is not None and len(self.icon_src):
            return f'<img src="{self.icon_src}" class="img-full" alt="" width="" height="" />'


class EntranceURL(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    url = models.URLField(blank=False, unique=True)
    linked_to = models.CharField(
        max_length=250,
        blank=False,
    )
    date_of_creation = models.DateTimeField(auto_now_add=True)
    greeting = models.TextField(blank=True, default="")
    accessed_by = models.ManyToManyField(
        Session,
        blank=True,
    )

    def __str__(self) -> str:
        return f"{self.url} -- {str(self.id)[:5]}"


class PageView(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    url = models.TextField(blank=False, unique=False)
    accessed = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    user_agent = models.TextField(blank=True, null=True, default="")
    ip = models.GenericIPAddressField(blank=False)
    referer = models.TextField(blank=True, default="", null=True)
    session = models.ForeignKey(
        Session,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self) -> str:
        return f"{self.page} -- {str(self.id)[:5]}"


class Media(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    url = models.TextField(blank=True, unique=False)
    image = models.ImageField(upload_to="media/", blank=True, null=True)

    def clean(self):
        if not(self.url or self.image):
            raise ValidationError(_("Media must have either url or image."))

    def __str__(self) -> str:
        return str(self.id)

    def get_media_url(self) -> str:
        if self.image:
            return self.image.url
        else:
            # TODO: for dalle query it from # GET https://api.openai.com/v1/files/{file_id}
            return self.url

catalog/forms.py
from django import forms


class UniqueUrlForm(forms.Form):
    template_name = "catalog/form_snippet.html"
    linked_to = forms.CharField(max_length=64, required=True)
    greeting = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "name": "body",
                "rows": "3",
                "cols": "25",
            }
        )
    )

catalog/views.py
from __future__ import annotations

import tempfile
from pathlib import Path

from django.contrib import messages
from django.http import HttpRequest, HttpResponseRedirect
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.vary import vary_on_cookie
from django.views.generic import View, TemplateView

from catalog.forms import UniqueUrlForm

# Self created Models
from catalog.models import Project, TechElement, EntranceURL
from catalog.templatetags.media import (
    generate_unique_url,
    get_db_user_view_level,
    get_session_data,
    get_user_view_level,
)


class PingView(View):
    def get(self, request):
        return HttpResponse("python/django", status=200)


@method_decorator(csrf_exempt, name="dispatch")
class ProjectsView(TemplateView):
    template_name = "catalog/projects.html"

    def get_context_data(self):
        user_view_level = get_user_view_level(request=self.request)
        projects = Project.objects.filter(view_level__lte=user_view_level + 1).order_by(
            "-created"
        )
        context = {
            "projects": projects,
            "user_view_level": user_view_level,
        }
        return context


@method_decorator(csrf_exempt, name="dispatch")
class ProjectView(generic.DetailView):
    template_name = "catalog/project.html"

    def get(self, request, id=None, *args, **kwargs):
        user_view_level = get_user_view_level(request=self.request)
        project = Project.objects.get(id=id)
        if project.view_level > user_view_level:
            messages.error(
                self.request,
                f"Sorry, you do not have the required view-level to see this project",
            )
            return HttpResponseRedirect(reverse("catalog:projects"))
        context = {
            "project": project,
            "techstack": project.techstack.all(),
            "user_view_level": user_view_level,
        }
        return render(request=request, template_name="catalog/project.html", context=context)


@method_decorator(csrf_exempt, name="dispatch")
class TechStackView(TemplateView):
    template_name = "catalog/techstack.html"

    def get_context_data(self, *args, **kwargs):
        user_view_level = get_user_view_level(request=self.request)
        techstack = TechElement.objects.exclude(
            id__in=TechElement.objects.filter(svg__lt=1, icon_src__lt=1).order_by(
                "name"
            ),
        )
        projects = Project.objects.filter(view_level__lte=user_view_level + 1).order_by(
            "view_level", "-created"
        )
        context = {
            "techstack": techstack,
            "projects": projects,
        }
        return context


@method_decorator(csrf_exempt, name="dispatch")
class TechElementView(generic.ListView):
    def get(self, request, tech_id=None, *args, **kwargs):
        assert tech_id is not None
        products = list(TechElement.objects.filter(id=tech_id).values())
        if len(products) == 0:
            return render(request, "main/home.html")
        return JsonResponse(products, safe=False)


# Create your views here.
tempfile = Path(tempfile.gettempdir(), "Count.txt")


@vary_on_cookie
def index(request: HttpRequest, *args, **kwargs):
    count = read_count()
    write_count(count + 1)
    context = {
        "overview": True,
        "view_count": count,
        "num_projects": Project.objects.all().count(),
        "num_techstack": TechElement.objects.all().count(),
    }
    if request.GET.get("not_implemented"):
        messages.add_message(request, 15, "This site is currently under construction.")
    return render(request=request, template_name="main/home.html", context=context)


@vary_on_cookie
def login(request: HttpRequest):
    return render(request, "main/login.html")


def read_count() -> int:
    if tempfile.exists():
        with open(tempfile) as fp:
            content = fp.readline()
        return int(content)
    return 0


def write_count(count: int) -> None:
    with open(tempfile, "w+") as fp:
        fp.write(str(count))


def handler404(request, *args, **kwargs) -> HttpResponse:
    messages.error(request, "Unknown page.")
    return HttpResponseRedirect("/")


def get_unique_url(request: HttpRequest | None) -> HttpResponse:
    """
    This function creates a new EntranceURL, and returns its url with the prefix "https://gahrb.dev/io/".
    The url is written into the db together with the request params with additional information where this url
    was published. The param must be specified with the key "linked_to". If the param is not specified, the timestamp
    is used as a fallback.
    :param request: HttpRequest
    :return: str
    """
    if request is not None and request.user.is_staff:
        # if this is a POST request we need to process the form data
        if request.method == "POST":
            # create a form instance and populate it with data from the request:
            form = UniqueUrlForm(request.POST)
            # check whether it's valid:
            if form.is_valid():
                form_data = form.cleaned_data
                new_url = generate_unique_url(request.get_host())
                entrance_element = EntranceURL.objects.create(
                    url=new_url,
                    linked_to=form_data["linked_to"],
                    greeting=form_data["greeting"],
                )
                context = {
                    "id": entrance_element.id,
                    "url": entrance_element.url,
                    "linked_to": entrance_element.linked_to,
                    "greeting": entrance_element.greeting,
                    "created": entrance_element.date_of_creation,
                }
                return render(
                    request=request,
                    template_name="catalog/unique_url_post.html",
                    context=context,
                )
        form = UniqueUrlForm()
        return render(
            request=request,
            template_name="catalog/unique_url_get.html",
            context={"form": form},
        )
    # Default: return 404
    return handler404(request)


@vary_on_cookie
def get_io_forward(request: HttpRequest, unique_url: str) -> HttpResponse:
    entrance_urls = EntranceURL.objects.all()
    for entrance_url in entrance_urls:
        if unique_url == entrance_url.url.split("/")[-1]:
            request.session["io"] = str(entrance_url.id)
            # Don't overwrite a view_level if it already exists
            request.session["view_level"] = max(2, get_db_user_view_level(request))
            messages.add_message(request, 10, entrance_url.greeting)
            entrance_url.accessed_by.add(request.session.session_key)
            break
    return HttpResponseRedirect("/")


@vary_on_cookie
def get_your_data(request: HttpRequest, user_id: int = None) -> HttpResponse:
    context = {}
    if (
        request.user.is_authenticated
        and request.user.id == user_id
        or request.user.is_staff
    ):
        session_data = get_session_data(
            request=request
        )
        context.update(
            {
                "collected_data": session_data,
            }
        )
    return render(request, "catalog/your_data.html", context=context)

catalog/templates/main/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include "main/menu.html" %}
    {% load static %}
    <meta name="description" content="Landing Page for gahrb.dev"/>
    <meta name="keywords" content="private, projects"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta charset="UTF-8"/>

    <title>gahrb.dev</title>
    {% block extrahead %}
    <link rel="shortcut icon" href="{% static 'img/dalle_gahrb_12.png' %}"/>
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0"/>
    <meta name="apple-mobile-web-app-capable" content="yes"/>

    <!-- Style -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}"/>
    <link rel="icon" href="{% static 'favicon.ico' %}"/>
    {% endblock extrahead %}

    <!-- fontawesome -->
    <script src="https://kit.fontawesome.com/5f11c1a928.js" crossorigin="anonymous"></script>
</head>
<body>

{% block header %}{% endblock header %}
{% block welcome %}{% endblock welcome %}

<main id="main" class="site-main">
    {% block content %}{% endblock content %}
    {% block overview %}{% endblock overview %}
</main>
<footer id="colophon" class="site-footer">
    {% include "main/footer.html" %}
    {% block footer %}{% endblock footer %}
</footer>

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js" type="application/javascript"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" type="application/javascript"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" type="application/javascript"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
<script src="https://unpkg.com/website-carbon-badges@1.1.3/b.min.js"  type="application/javascript" defer></script>
<script src="{% static 'js/jquery.countTo.min.js' %}" type="application/javascript"></script>
<script src="{% static 'js/jquery.shuffle.min.js' %}" type="application/javascript"></script>
<script src="{% static 'js/script.js' %}" type="application/javascript"></script>
{% endblock scripts %}
</body>
</html>

catalog/templates/main/footer.html
{% block footer %}
<footer class="bg-dark text-center text-white">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">

      {% if user.is_authenticated %}
      <a class="btn btn-blue btn-outline-light btn-floating m-1" href="https://gitlab.com/gahrb" role="button"
        ><i class="fa-brands fa-gitlab"></i
      ></a>
      <a class="btn btn-blue btn-outline-light btn-floating m-1" href="https://www.linkedin.com/in/gahr-bernhard/" role="button"
        ><i class="fa-brands fa-linkedin"></i
      ></a>
      <a class="btn btn-blue btn-outline-light btn-floating m-1" href="https://github.com/gahrb" role="button"
        ><i class="fa-brands fa-github"></i
      ></a>
      {% endif %}
      <a class="btn btn-blue btn-outline-light btn-floating m-1" href="https://twitter.com/gahrb" role="button"
      ><i class="fa-brands fa-twitter"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>

  <!-- Project Badges -->
  <div class="container p-4 pb-0">
      <div class="row justify-content-center">
    <ul class="list-inline">
        <li class="list-inline-item align-top">
            <div class="carbonbadge" id="wcb"></div>
        </li>
        <li class="list-inline-item align-top">
            <a class="gl-mr-3" data-qa-link-url="https://gitlab.com/gahrb1/web_presence/-/releases/permalink/latest"
               data-qa-selector="badge_image_link"
               href="https://gitlab.com/gahrb1/web_presence/-/releases/permalink/latest" rel="noopener noreferrer"
               target="_blank">
                <img alt="Project badge" aria-hidden="" class="project-badge" height=""
                     src="https://gitlab.com/gahrb1/web_presence/-/badges/release.svg?key_width=130" width=""/>
            </a>
        </li>
        <li class="list-inline-item align-top">
            <a class="gl-mr-3" data-qa-link-url="https://gitlab.com/gahrb1/web_presence"
               data-qa-selector="badge_image_link" href="https://gitlab.com/gahrb1/web_presence"
               rel="noopener noreferrer" target="_blank">
                <img alt="Project badge"
                     aria-hidden=""
                     class="project-badge"
                     height=""
                     src="https://user-content.gitlab-static.net/e7b1487736a40a602d6d6861a3e0d4f95392e460/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f636f64652532307374796c652d626c61636b2d3030303030302e737667"
                     width=""/>
            </a>
        </li>
    </ul>
    </div>
  </div>

    <div class="text-center p-3" >
        <p>Your Data:</p>
        <p>{% if user.is_authenticated %}
            <a class="text-white" href="{% url 'catalog:session_data' user.id %}">Logged in as
            {{ user }}</a>
            {% else %}
            <a class="text-white" href="{% url 'catalog:session_data' %}">Not logged in: {{ user }}</a>
            {% endif %}
        </p>
    </div>
  <div class="text-center p-3">
    ©2022 Copyright:
    <a href="{% url 'catalog:home' %}?not_implemented=True">gahrb.dev</a>
  </div>
</footer>
{% endblock footer %}

catalog/templates/main/home.html
{% extends "main/base_generic.html" %}
{% load static %}

{% block welcome %}
<div id="hero" class="hero overlay">
    <div class="container">
    <div class="hero-content">
        <div class="hero-text">
            <h1>Welcome to gahrb.dev</h1>
            <p>This page is mainly for my personal use.</p>
        </div>
    </div>
    </div>
</div>
{% endblock welcome %}

{% block content %}
<section class="site-section section-features">
    <div class="container" id="projects">
        <h2>Projects</h2>
        <ul class="portfolio-sorting list-unstyled">
            <li class="list-inline-item">
                <p>Find all projects. Finalized, deprecated, or actively maintained.</p>
            </li>
        </ul>
        <a href="{% url 'catalog:projects' %}" class="btn btn-gray btn-border">
            View Projects
        </a>
        <img class="rounded"
             src="{% static 'img/dalle_gahrb_14.png' %}"
             alt="Projects wallpaper" height="" width=""/>
    </div>
</section>

<section class="site-section gray-bg section-features">
    <div class="container" id="techstack">
        <h2>Tech Stack</h2>
        <ul class="list-unstyled">
            <li class="list-inline-item">
                <p>Find the techstack used in all projects.</p>
            </li>
        </ul>
        <a href="{% url 'catalog:techstack' %}" class="btn btn-gray btn-border">
            View Tech Stack
        </a>
        <img class="rounded"
             src="{% static 'img/dalle_gahrb_13.png' %}"
             alt="Tech stack wallpaper" height="" width=""/>
    </div>
</section>
{% endblock content %}

{% block overview %}
{% include "main/overview.html" %}
{% endblock overview %}

catalog/templates/main/login.html
{% extends "main/base_generic.html" %}
{% load static %}
{% load socialaccount %}
{% block welcome %}
<div id="subpage-hero" class="subpage-hero overlay">
    <div class="container">
    <div class="hero-content">
        <div class="hero-text text-center">
            <h1>login page</h1>
            <p>Connect using one of the following social platform providers</p>
        </div>
    </div>
    </div>
</div>
{% endblock welcome %}
{% block content %}
<div class="subpage-site-section">
    <div class="container">
    {% if not user.is_authenticated %}
    <h3>Platform providers:</h3>
    <ul class="list-unstyled">
        {% get_providers as socialaccount_providers %}
        {% for provider in socialaccount_providers %}
        <li class="list-item">
            <a title="{{ provider.name }}" class="btn btn-grey socialaccount_provider {{ provider.id }}"
               href="{% provider_login_url provider.id process="login" scope=scope auth_params=auth_params %}">
                {{ provider.name }}
            </a>
        </li>
        {% endfor %}
    </ul>
    {% endif %}
    </div>
</div>
{% endblock content %}

catalog/templates/main/menu.html
{% load static %}

{% block header %}
{% with request.resolver_match.url_name as url_name %}
<header id="masthead">
    <section id="navigation">
        <nav class="navbar flex-column flex-sm-row">
            <a class="navbar-brand" href="{% url 'catalog:home' %}">
                <img alt="gahrb.dev logo"
                     src="{% static 'img/dalle_gahrb_12.png' %}"
                     class="d-inline-block align-top"
                     width="30" height="30"/>
                gahrb.dev
            </a>

            <ul class="nav nav-tabs justify-content-end">
                <li class="nav-item">
                    <a class="nav-link{% if url_name == 'home' %} active{% endif %}"
                       href="{% url 'catalog:home' %}">
                        Home
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle{% if url_name == 'projects' or url_name == 'techstack' %} active{% endif %}"
                       data-toggle="dropdown"
                       href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Content
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item{% if url_name == 'projects' %} active{% endif %}"
                           href="{% url 'catalog:projects' %}">
                            Projects
                        </a>
                        <a class="dropdown-item{% if url_name == 'techstack' %} active{% endif %}"
                           href="{% url 'catalog:techstack' %}">
                            Tech Stack
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item disabled{% if url_name == 'analysis' %} active{% endif %}"
                           href="{% url 'catalog:home' %}#analysis">Analysis</a>
                        {% if user.is_staff %}
                        <a class="dropdown-item disabled{% if url_name == 'ping' %} active{% endif %}"
                           href="{% url 'catalog:ping' %}">Ping</a>
                        {% endif %}
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link{% if url_name == 'login' %} active{% endif %}"
                       href="{% if user.is_authenticated %} {% url 'account_logout' %} {% else %}{% url 'catalog:login' %}{% endif %}">
                        {% if user.is_authenticated %}Logout{% else %}Login{% endif %}
                    </a>
                </li>
                {% if user.is_authenticated or debug %}
                <li class="nav-item">
                    <a class="nav-link"
                       href="{% url 'admin:index' %}">
                        Admin
                    </a>
                </li>
                {% endif %}
                {% if user.is_staff or debug %}
                <li class="nav-item">
                    <a class="nav-link{% if url_name == 'unique_url' %} active{% endif %}"
                       href="{% url 'catalog:unique_url' %}">
                        Get Unique URL
                    </a>
                </li>
                {% endif %}
            </ul>
            <!-- form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2 disabled" type="search" placeholder="Search" aria-label="Search"/>
              <button class="btn btn-outline-success my-2 my-sm-0 disabled" type="submit">Search</button>
            </form -->
        </nav>
    </section>
</header>
{% endwith %}
{% endblock header %}

catalog/templates/main/messages.html
{% block messages %}
{% if messages %}
<ul class="nav justify-content-center">
    {% for message in messages|slice:':1'|dictsortreversed:"level" %}
    <li class="list-inline-item ">
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
            {% if DEFAULT_MESSAGE_LEVELS.INFO <= message.level and message.level < DEFAULT_MESSAGE_LEVELS.WARNING %}Notice: {% endif %}
            {% if DEFAULT_MESSAGE_LEVELS.WARNING <= message.level and message.level < DEFAULT_MESSAGE_LEVELS.ERROR %}Warning: {% endif %}
            {% if message.level >= DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        </div>
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock messages %}

catalog/templates/main/overview.html
{% load static %}
{% load media %}
{% block overview %}
{% if overview %}
<section class="section-features">
    <div class="container container-bg" id="overview">
        <h2 class="text-center">Content</h2>
        <div class="row justify-content-center">
            {% if num_projects %}
            <div class="counter-item col-lg-3 col-md-3 col-xs-6">
                <h2 class="counter" data-to="{{ num_projects }}" data-speed="2000">0</h2>
                <h3>Number of Projects</h3>
            </div>
            {% endif %}
            {% if num_techstack %}
            <div class="counter-item col-lg-3 col-md-3 col-xs-6">
                <h2 class="counter" data-to="{{ num_techstack }}" data-speed="2000">0</h2>
                <h3>Tech stack size</h3>
            </div>
            {% endif %}
            {% if view_count %}
            <div class="counter-item col-lg-3 col-md-3 col-xs-6">
                <h2 class="counter" data-to="{{ view_count }}" data-speed="1000">0</h2>
                <h3>Views on this container image</h3>
            </div>
            {% endif %}
        </div>
    </div>
</section>

{% endif %}
{% endblock overview %}