catalog/urls.py
from django.urls import path

from catalog import views

urlpatterns = [
    path("", views.index, name="index"),
    path("index.html", views.index, name="home"),
    path("ping.html", views.index, name="ping"),
    path("login.html", views.login, name="login"),
    path("about.html", views.index, name="about"),
    path("stats/", views.PingView.as_view(), name="stats"),
    path("ping/", views.PingView.as_view(), name="ping"),
    path("projects/", views.ProjectsView.as_view(), name="projects"),
    path("project/<uuid:id>/", views.ProjectView.as_view(), name="project"),
    path("techstack/", views.TechStackView.as_view(), name="techstack"),
    path("techelement/<uuid:id>/", views.TechElementView.as_view(), name="techelem"),
    path("unique_url/", views.get_unique_url, name="unique_url"),
    path("your_data/", views.get_your_data, name="session_data"),
    path("your_data/<int:user_id>", views.get_your_data, name="session_data"),
]

landing_page/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic import RedirectView

from catalog import views

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    ###
    # Admin related urls
    ###
    path(
        "admin/password_reset/",
        auth_views.PasswordResetView.as_view(),
        name="admin_password_reset",
    ),
    path(
        "admin/password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

urlpatterns += [
    path("home/", include(("catalog.urls", "catalog"), namespace="catalog")),
    # All Auth urls
    path("accounts/", include("allauth.urls")),
]

# The default root url should point to catalog
urlpatterns += [
    path("", RedirectView.as_view(url="home/", permanent=False)),
    path("io/<str:unique_url>", views.get_io_forward, name="io_forward"),
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "catalog.views.handler404"
# handler500 = 'catalog.views.handler404'

catalog/models.py
from __future__ import annotations

from importlib.resources import _

from django.conf import settings
from django.contrib.sessions.models import Session
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.safestring import mark_safe
import uuid


class AppAuthor(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=250)
    email = models.EmailField()

    def __str__(self):
        return f"{self.name} -- {str(self.id)[:5]}"


class Project(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=250)
    description = models.TextField(max_length=2**14)
    active = models.BooleanField()
    link = models.URLField()
    created = models.DateField(auto_now_add=False, blank=False)
    view_level = models.IntegerField(default=1)
    author = models.ForeignKey("AppAuthor", on_delete=models.SET_NULL, null=True)
    techstack = models.ManyToManyField("TechElement")
    media = models.ManyToManyField("Media")

    DEV_STATUS = (
        ("m", "Maintained"),
        ("f", "Finalized"),
        ("d", "Deprecated"),
        ("p", "Planned"),
    )

    status = models.CharField(
        max_length=1,
        choices=DEV_STATUS,
        blank=True,
        default="p",
        help_text="Project status",
    )

    def __str__(self):
        return f"{self.name} -- {str(self.id)[:5]}"

    def escape_name(self):
        return str(self.name).replace(" ", "_")

    class Meta:
        ordering = ["-created"]


class TechElement(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=250)
    icon_src = models.URLField(blank=True)
    svg = models.TextField(blank=True)

    def __str__(self) -> str:
        return f"{self.name} -- {str(self.id)[:5]}"

    @mark_safe
    def icon_to_html(self) -> str | None:
        if self.svg is not None and len(self.svg):
            return f"""
            <div class="img-full">
            <svg id=\"{self.name}-svg\" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 51 51" preserveAspectRatio="none">
             {self.svg}
            </svg>
            </div>
            """
        elif self.icon_src is not None and len(self.icon_src):
            return f'<img src="{self.icon_src}" class="img-full" alt="" width="" height="" />'


class EntranceURL(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    url = models.URLField(blank=False, unique=True)
    linked_to = models.CharField(
        max_length=250,
        blank=False,
    )
    date_of_creation = models.DateTimeField(auto_now_add=True)
    greeting = models.TextField(blank=True, default="")
    accessed_by = models.ManyToManyField(
        Session,
        blank=True,
    )

    def __str__(self) -> str:
        return f"{self.url} -- {str(self.id)[:5]}"


class PageView(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    url = models.TextField(blank=False, unique=False)
    accessed = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    user_agent = models.TextField(blank=True, null=True, default="")
    ip = models.GenericIPAddressField(blank=False)
    referer = models.TextField(blank=True, default="", null=True)
    session = models.ForeignKey(
        Session,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self) -> str:
        return f"{self.page} -- {str(self.id)[:5]}"


class Media(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    url = models.TextField(blank=True, unique=False)
    image = models.ImageField(upload_to="media/", blank=True, null=True)

    def clean(self):
        if not(self.url or self.image):
            raise ValidationError(_("Media must have either url or image."))

    def __str__(self) -> str:
        return str(self.id)

    def get_media_url(self) -> str:
        if self.image:
            return self.image.url
        else:
            # TODO: for dalle query it from # GET https://api.openai.com/v1/files/{file_id}
            return self.url

catalog/forms.py
from django import forms


class UniqueUrlForm(forms.Form):
    template_name = "catalog/form_snippet.html"
    linked_to = forms.CharField(max_length=64, required=True)
    greeting = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "name": "body",
                "rows": "3",
                "cols": "25",
            }
        )
    )

catalog/views.py
from __future__ import annotations

import tempfile
from pathlib import Path

from django.contrib import messages
from django.http import HttpRequest, HttpResponseRedirect
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.vary import vary_on_cookie
from django.views.generic import View, TemplateView

from catalog.forms import UniqueUrlForm

# Self created Models
from catalog.models import Project, TechElement, EntranceURL
from catalog.templatetags.media import (
    generate_unique_url,
    get_db_user_view_level,
    get_session_data,
    get_user_view_level,
)


class PingView(View):
    def get(self, request):
        return HttpResponse("python/django", status=200)


@method_decorator(csrf_exempt, name="dispatch")
class ProjectsView(TemplateView):
    template_name = "catalog/projects.html"

    def get_context_data(self):
        user_view_level = get_user_view_level(request=self.request)
        projects = Project.objects.filter(view_level__lte=user_view_level + 1).order_by(
            "-created"
        )
        context = {
            "projects": projects,
            "user_view_level": user_view_level,
        }
        return context


@method_decorator(csrf_exempt, name="dispatch")
class ProjectView(generic.DetailView):
    template_name = "catalog/project.html"

    def get(self, request, id=None, *args, **kwargs):
        user_view_level = get_user_view_level(request=self.request)
        project = Project.objects.get(id=id)
        if project.view_level > user_view_level:
            messages.error(
                self.request,
                f"Sorry, you do not have the required view-level to see this project",
            )
            return HttpResponseRedirect(reverse("catalog:projects"))
        context = {
            "project": project,
            "techstack": project.techstack.all(),
            "user_view_level": user_view_level,
        }
        return render(request=request, template_name="catalog/project.html", context=context)


@method_decorator(csrf_exempt, name="dispatch")
class TechStackView(TemplateView):
    template_name = "catalog/techstack.html"

    def get_context_data(self, *args, **kwargs):
        user_view_level = get_user_view_level(request=self.request)
        techstack = TechElement.objects.exclude(
            id__in=TechElement.objects.filter(svg__lt=1, icon_src__lt=1).order_by(
                "name"
            ),
        )
        projects = Project.objects.filter(view_level__lte=user_view_level + 1).order_by(
            "view_level", "-created"
        )
        context = {
            "techstack": techstack,
            "projects": projects,
        }
        return context


@method_decorator(csrf_exempt, name="dispatch")
class TechElementView(generic.ListView):
    def get(self, request, tech_id=None, *args, **kwargs):
        assert tech_id is not None
        products = list(TechElement.objects.filter(id=tech_id).values())
        if len(products) == 0:
            return render(request, "main/home.html")
        return JsonResponse(products, safe=False)


# Create your views here.
tempfile = Path(tempfile.gettempdir(), "Count.txt")


@vary_on_cookie
def index(request: HttpRequest, *args, **kwargs):
    count = read_count()
    write_count(count + 1)
    context = {
        "overview": True,
        "view_count": count,
        "num_projects": Project.objects.all().count(),
        "num_techstack": TechElement.objects.all().count(),
    }
    if request.GET.get("not_implemented"):
        messages.add_message(request, 15, "This site is currently under construction.")
    return render(request=request, template_name="main/home.html", context=context)


@vary_on_cookie
def login(request: HttpRequest):
    return render(request, "main/login.html")


def read_count() -> int:
    if tempfile.exists():
        with open(tempfile) as fp:
            content = fp.readline()
        return int(content)
    return 0


def write_count(count: int) -> None:
    with open(tempfile, "w+") as fp:
        fp.write(str(count))


def handler404(request, *args, **kwargs) -> HttpResponse:
    messages.error(request, "Unknown page.")
    return HttpResponseRedirect("/")


def get_unique_url(request: HttpRequest | None) -> HttpResponse:
    """
    This function creates a new EntranceURL, and returns its url with the prefix "https://gahrb.dev/io/".
    The url is written into the db together with the request params with additional information where this url
    was published. The param must be specified with the key "linked_to". If the param is not specified, the timestamp
    is used as a fallback.
    :param request: HttpRequest
    :return: str
    """
    if request is not None and request.user.is_staff:
        # if this is a POST request we need to process the form data
        if request.method == "POST":
            # create a form instance and populate it with data from the request:
            form = UniqueUrlForm(request.POST)
            # check whether it's valid:
            if form.is_valid():
                form_data = form.cleaned_data
                new_url = generate_unique_url(request.get_host())
                entrance_element = EntranceURL.objects.create(
                    url=new_url,
                    linked_to=form_data["linked_to"],
                    greeting=form_data["greeting"],
                )
                context = {
                    "id": entrance_element.id,
                    "url": entrance_element.url,
                    "linked_to": entrance_element.linked_to,
                    "greeting": entrance_element.greeting,
                    "created": entrance_element.date_of_creation,
                }
                return render(
                    request=request,
                    template_name="catalog/unique_url_post.html",
                    context=context,
                )
        form = UniqueUrlForm()
        return render(
            request=request,
            template_name="catalog/unique_url_get.html",
            context={"form": form},
        )
    # Default: return 404
    return handler404(request)


@vary_on_cookie
def get_io_forward(request: HttpRequest, unique_url: str) -> HttpResponse:
    entrance_urls = EntranceURL.objects.all()
    for entrance_url in entrance_urls:
        if unique_url == entrance_url.url.split("/")[-1]:
            request.session["io"] = str(entrance_url.id)
            # Don't overwrite a view_level if it already exists
            request.session["view_level"] = max(2, get_db_user_view_level(request))
            messages.add_message(request, 10, entrance_url.greeting)
            entrance_url.accessed_by.add(request.session.session_key)
            break
    return HttpResponseRedirect("/")


@vary_on_cookie
def get_your_data(request: HttpRequest, user_id: int = None) -> HttpResponse:
    context = {}
    if (
        request.user.is_authenticated
        and request.user.id == user_id
        or request.user.is_staff
    ):
        session_data = get_session_data(
            request=request
        )
        context.update(
            {
                "collected_data": session_data,
            }
        )
    return render(request, "catalog/your_data.html", context=context)

catalog/templates/catalog/form_snippet.html
<div class="container">
{% for field in form %}
        <p>{{ field.errors }}</p>
        <p>{{ field.label_tag }} {{ field }}</p>
{% endfor %}
</div>

catalog/templates/catalog/project.html
{% extends "main/base_generic.html" %}
{% load static %}
{% load media %}

{% block welcome %}
<div id="hero" class="hero overlay" >
    <div class="container">
    <div class="hero-content">
        <div class="hero-text text-left">
            <p>Project:</p>
            <h1>{{ project.name }}</h1>
        </div>
    </div>
    </div>
</div>
{% endblock welcome %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="post-content">
                <p>{{ project.description }}</p>
            </div>
        </div>
        <div class="col-md-4">
            <div class="post-content border border-secondary rounded">
                <h3 class="post-title">Project Card</h3>
                <p>Project Name: {{ project.name }}</p>
                <p>Project Link: <a class="read-more" href="{{ project.link }}">{{ project.link }}</a>
                    <i class="fa-solid fa-link fa-fade"></i></p>
                <p>Project Status: {{ project.get_status_display }}</p>
            </div>
        </div>

        {% if project.media.all %}
        <div class="col-md-12">
            <div class="post-content">
                <h3 class="post-title">Project Media</h3>
                <div class="row">
                    {% for media in project.media.all %}
                    <div class="col-md-4">
                        <div class="post-content">
                            <img src="{{ media.get_media_url }}" class="rounded mx-auto d-block" alt="" height="200" width="200" />
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}

        <!-- Techstack of the project -->
        <div class="col-md-12">
            <div class="post-content">
                <h3 class="post-title">Techstack</h3>
                <div id="grid" class="row">
                    {% for element in techstack %}
                    <div class="col-lg-3 col-md-4 col-xs-6"
                        data-groups=[{% for project in element.project_set.all %}"{{ project.escape_name }}",{% endfor %}"all"]>
                       <div class="portfolio-item" id="{{ element.escape_name }}">
                         {{ element.icon_to_html }}
                         <h4 class="portfolio-item-title">{{ element.name }}</h4>
                             <a href="{% url 'catalog:techstack' %}#{{ element.escape_name }}" >
                             <i class="fa fa-arrow-right" aria-hidden="true">
                             </i></a>
                       </div>
                     </div>
                    {% endfor %}
                </div>
                {% if techstack|length > 4 %}
                <div class="text-center">
                    <a class="btn btn-gray" href="#" id="loadMore">Load More</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

catalog/templates/catalog/projects.html
{% extends "main/base_generic.html" %}
{% load static %}
{% load media %}

{% block welcome %}
<div id="hero" class="subpage-hero overlay" >
    <div class="container">
    <div class="hero-content">
        <div class="hero-text">
            <h1>Projects</h1>
        </div>
    </div>
    </div>
</div>
{% endblock welcome %}
{% block content %}

{% if projects %}
<section class="site-section section-portfolio">
    <div class="container">
      <div class="text-center">
        <h2 class="heading-separator">Latest Work</h2>
        <p class="subheading-text">Below, you can find all projects. To see more of them you may need to be logged in, or have been unlocked.</p>
          <p class="subheading-text"></p>
      </div>

      <div class="row">
      {% for project_iter in projects %}
         <article class="blog-post" id="{{ project_iter.id }}">
            {% if project_iter|get_blur:user_view_level %}
             <a href="{% url 'catalog:projects' %}#{{ project_iter.id }}">
                <img src="{% static forloop.counter|get_dalle_img %}"
                     class="img-res"
                     alt=""
                     height="80"
                     width="80" />
            </a>
             {% else %}
             <a href="{% url 'catalog:project' project_iter.id %}">
                 <img src="{% get_sample_img %}"
                     class="img-res"
                     alt=""
                     height="80"
                     width="80" />
            </a>
             {% endif %}
            <div {% if project_iter|get_blur:user_view_level %}
                 class="post-content post-blur"
                 {% else %}
                 class="post-content"
                 {% endif %}>
                <h3 class="post-title"><a href="{% url 'catalog:project' project_iter.id %}">{{ project_iter.name }}</a></h3>
                {% if not project_iter|get_blur:user_view_level %}
                <p>
                <a class="read-more"
                   href="{{ project_iter.link }}">
                    Visit project directly
                    <i class="fa-solid fa-link fa-fade"></i>
                </a>
                </p>
                {% else %}
                <p>More information coming soon...</p>
                {% endif %}
                <div class="post-meta">
                    {% if not project_iter|get_blur:user_view_level %}
                    <span class="post-author">
                        Status: {{ project_iter.get_status_display }}
                    </span>
                    <span class="post-date">
                        Start Date: {{ project_iter.created }}
                    </span>
                    <span class="post-category">
                        Tech Elements: {{ project_iter|get_ts_len }}
                    </span>
                    {% else %}
                    <span class="post-author">
                    Hi there! You looked into the source code?!?
                    </span>
                    {% endif %}
                </div>
            </div>
            {% if project_iter|get_blur:user_view_level %}
            <p>
            <a class="read-more" href="{% url 'catalog:projects' %}#{{ project_iter.id }}">
                Hidden project
            </a>
            </p>
            {% endif %}
        </article>

      {% endfor %}
      </div>
    </div>
  </section>
{% else %}
<h3>No projects defined yet</h3>
{% endif %}
{% endblock content %}

catalog/templates/catalog/techstack.html
{% extends "main/base_generic.html" %}
{% load static %}
{% load media %}

{% block welcome %}
<div id="hero" class="subpage-hero overlay" >
    <div class="container">
    <div class="hero-content">
        <div class="hero-text">
            <h1>Tech Stack</h1>
        </div>
    </div>
    </div>
</div>
{% endblock welcome %}

{% block content %}
{% if techstack %}
<section class="site-section subpage-site-section section-portfolio">
  <div class="container">
    <div class="text-center">
        <h2 class="heading-separator">Utilized Tech Elements</h2>
        <p class="subheading-text">Select a project to see its tech stack.</p>
        <h2 class="heading-separator"></h2>
      </div>
  </div>

  <div class="container">
      <ul class="portfolio-sorting list-inline text-center">
          <li class="list-inline-item"><a href="#" class="btn btn-gray active" data-group="all">All</a></li>
          {% for project in projects %}
          <li class="list-inline-item"><a href="#" class="btn btn-gray {% if project|get_blur %}btn-blur{% endif %}" data-group="{{ project.escape_name }}">{{ project.name }}</a></li>
          {% endfor %}
      </ul>

      <div id="grid" class="row">
          {% for element in techstack %}
          <div class="col-lg-3 col-md-4 col-xs-6"
              data-groups=[{% for project in element.project_set.all %}"{{ project.escape_name }}",{% endfor %}"all"]>
             <div class="portfolio-item" id="{{ element.escape_name }}">
               {{ element.icon_to_html }}
               <h4 class="portfolio-item-title">{{ element.name }}</h4>
                   <a href="{% url 'catalog:techstack' %}#{{ element.escape_name }}" >
                   <i class="fa fa-arrow-right" aria-hidden="true">
                   </i></a>
             </div>
           </div>
          {% endfor %}
      </div>
      <div class="text-center">
          <a class="btn btn-gray" href="#" id="loadMore">Load More</a>
      </div>
  </div>
</section>
{% else %}
<h3>No techstack defined yet</h3>
{% endif %}
{% endblock content %}

catalog/templates/catalog/unique_url_get.html
{% extends "main/base_generic.html" %}
{% load static %}
{% load media %}

{% block content %}
<section class="site-section section-portfolio" xmlns="http://www.w3.org/1999/html">
    <div class="container">
      <div class="text-center">
        <h2 class="heading-separator">Generate Link</h2>
        <form action="{% url 'catalog:unique_url' %}" method="post">
          {% csrf_token %}
          {{ form }}
          <input type="submit" value="submit" class="btn btn-blue btn-border"/>
        </form>
      </div>
    </div>
</section>
{% endblock content %}

catalog/templates/catalog/unique_url_post.html
{% extends "main/base_generic.html" %}
{% load static %}
{% load media %}

{% block content %}
<section class="site-section section-portfolio" xmlns="http://www.w3.org/1999/html">
    <div class="container">
      <div class="text-center">
        <h2 class="heading-separator">Generated Link </h2>
          <p class="subheading-text">
          ID: {{ id }}
          </p>
          <p class="subheading-text">
          Content: {{ linked_to }}
          </p>
          <p class="subheading-text">
          Created at: {{ created }}</p>
          <p class="subheading-text">
          Url: {{ url }}
          </p>
          <p class="subheading-text">
          Greeting: {{ greeting }}
          </p>
      </div>
    </div>
</section>
{% endblock content %}

catalog/templates/catalog/your_data.html
{% extends "main/base_generic.html" %}
{% load static %}
{% load media %}

{% block welcome %}
<section class="site-section section-portfolio">
    <div class="container">
    <div class="hero-content">
        <div class="hero-text">
            <h1>Your data</h1>
            <p>Find below the stored data associated with you.</p>
        </div>
    </div>
    </div>
</section>
{% endblock welcome %}

{% block content %}
<section class="site-section">
    <div class="container" id="data">
        <h2>Data</h2>
        <ul class="portfolio-sorting list-unstyled">
            <li class="list-item">
                {% if user.is_authenticated %}
                Associated User: <p>{{ user.username }}</p>
                {% else %}
                User not assiciated: <p>{{ user }}</p>
                {% endif %}
            </li>
            <li class="list-item">
                Current Session Data:
                <ul class="portfolio-sorting list-unstyled">
                    {% for item in request.session.items %}
                    {% if item.0|slice:":1" != "_" %}
                    <li class="list-inline-item">
                        <p>{{ item }}</p>
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul>
            </li>
            {% if collected_data %}
            <li class="list-item">
                <p>Previously collected data: {{ collected_data }}</p>
            </li>
            {% endif %}
        </ul>
    </div>
</section>
{% endblock content %}